// <auto-generated />
using System;
using IssWebRazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssWebRazorApp.Migrations
{
    [DbContext(typeof(IssWebRazorAppContext))]
    [Migration("20200320103831_Initial0320")]
    partial class Initial0320
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("IssWebRazorApp.Data.CategoryData", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Session")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.PlaybookData", b =>
                {
                    b.Property<int>("PlaybookSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenceFormationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntroduceStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastUpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseFormationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayCallName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayDesignUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaybookSystemId");

                    b.ToTable("Playbooks");
                });
#pragma warning restore 612, 618
        }
    }
}
