// <auto-generated />
using System;
using IssWebRazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssWebRazorApp.Migrations
{
    [DbContext(typeof(IssWebRazorAppContext))]
    partial class IssWebRazorAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("IssWebRazorApp.Data.CategoryData", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Session")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.FootballNoteData", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastUpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCategoryCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetNoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPlaybookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetSession")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("LastUpdateUserId");

                    b.ToTable("FootballNotes");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.PlaybookData", b =>
                {
                    b.Property<int>("PlaybookSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenceFormationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntroduceStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastUpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffenseFormationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayCallName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayDesignUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaybookSystemId");

                    b.HasIndex("Category");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("LastUpdateUserId");

                    b.ToTable("Playbooks");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.PositionData", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.ScheduleAnswerData", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleId", "UserId");

                    b.ToTable("ScheduleAnswers");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.ScheduleData", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.UserData", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameKanji")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameRoman")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("LastNameKanji")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNameRoman")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemRole")
                        .HasColumnType("TEXT");

                    b.Property<int>("UniformNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserType")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IssWebRazorApp.Data.FootballNoteData", b =>
                {
                    b.HasOne("IssWebRazorApp.Data.UserData", "CreateUserData")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssWebRazorApp.Data.UserData", "LastUpdateUserData")
                        .WithMany()
                        .HasForeignKey("LastUpdateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IssWebRazorApp.Data.PlaybookData", b =>
                {
                    b.HasOne("IssWebRazorApp.Data.CategoryData", "CategoryData")
                        .WithMany()
                        .HasForeignKey("Category");

                    b.HasOne("IssWebRazorApp.Data.UserData", "CreateUserData")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IssWebRazorApp.Data.UserData", "LastUpdateUserData")
                        .WithMany()
                        .HasForeignKey("LastUpdateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IssWebRazorApp.Data.UserData", b =>
                {
                    b.HasOne("IssWebRazorApp.Data.PositionData", "PositionData")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
